[package]
name = "markadd"
version = "0.0.1"
edition = "2024"

[[bin]]
name = "markadd"
path = "src/main.rs"

[dependencies]
chrono = { version = "0.4.42", features = ["clock"] }
clap = { version = "4.5.51", features = ["derive"] }
markadd-core = { path = "../core" }
regex = "1.12.2"

[dev-dependencies]
assert_cmd = "2.1.1"
insta = { version = "1.43.2", features = ["glob"] }
predicates = "3.1.3"
regex = "1.12.2"
tempfile = "3.23.0"
