[package]
name = "markadd"
version = "0.0.1"
edition = "2024"

[[bin]]
name = "markadd"
path = "src/main.rs"

[dependencies]
markadd-core = { path = "../core" }

[dev-dependencies]
assert_cmd = "2.1.1"
insta = { version = "1.43.2", features = ["glob"] }
predicates = "3.1.3"
regex = "1.12.2"
tempfile = "3.23.0"
