[package]
name = "markadd-core"
version = "0.0.1"
edition = "2024"

[lib]
name = "markadd_core"
path = "src/lib.rs"

[dependencies]
dirs = "6.0.0"
serde = { version = "1.0.228", features = ["derive"] }
shellexpand = "3.1.1"
thiserror = "2.0.17"
toml = "0.9.8"

[dev-dependencies]
rstest = "0.26.1"
tempfile = "3.23.0"
